####################################################################
services:
  database:
    build: database
    container_name: database
    env_file:
      - database/.env
    volumes:
      - database:/database
####################################################################
  server-web:
    build: server-web
    container_name: web
    working_dir: /web
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    env_file:
      - server-web/.env
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./server-web
        target: /web
####################################################################
  server-amqp:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    depends_on:
      - database
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - server-amqp/.env
    volumes:
      - amqp:/amqp
####################################################################
  server-mqtt:
    build: server-mqtt
    container_name: mosquitto
    depends_on:
      - database
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt:/mqtt
####################################################################
  applivreur:
    build: applivreur
    container_name: applivreur
    command: sh -c "python app.py"
    depends_on:
      - database
    volumes:
      - applivreur:/app

#############################LesVolumes#############################
volumes:
  database:
  amqp:
  mqtt:
  applivreur: